---
- name: Configurar RPM do repositorio oficial Zabbix 7.0 para Rocky 9
  dnf:
    name: https://zabbix.com
    state: present
    disable_gpg_check: yes

- name: Instalar pacote do Zabbix Agent via DNF
  dnf:
    name: zabbix-agent
    state: present

- name: Ajustar parametros do zabbix_agentd.conf
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^Server=', line: 'Server=127.0.0.1,192.168.56.10' }
    - { regexp: '^ServerActive=', line: 'ServerActive=127.0.0.1' }
    - { regexp: '^Hostname=', line: 'Hostname=lab01' }
  notify: Restart Zabbix Agent Service

- name: Iniciar e habilitar o Zabbix Agent no boot
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes
