---
- name: Instalar utilitarios de SRE
  dnf:
    name:
      - dnf-plugins-core
      - curl
      - git
      - tar             
      - gzip            
      - python3-pip
      - epel-release
    state: present
    update_cache: yes

- name: Desativar firewalld local do laboratorio
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: true
