---
- name: Instalar repositorio EPEL
  dnf:
    name: epel-release
    state: present

- name: Instalar utilitarios de SRE
  dnf:
    name:
      - curl
      - htop
      - git
      - unzip
      - net-tools
      - tar
    state: present
    update_cache: yes

- name: Desativar firewalld local do laboratorio
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: true
