apiVersion: 1

datasources:
  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    url: http://zabbix-web-nginx:8080/api_jsonrpc.php
    jsonData:
      username: Admin
      password: zabbix
      trends: true
      cacheTTL: 1h
      trendsFrom: 7d
      dbConnectionEnable: false
    secureJsonData: {}
    isDefault: true
    editable: true