---
- name: Criar diretório da aplicação
  ansible.builtin.file:
    path: /opt/observability/sample-app
    state: directory
    mode: '0755'

- name: Copiar Docker Compose da aplicação
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/observability/sample-app/docker-compose.yml
    mode: '0644'

- name: Subir aplicação corporativa de teste
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /opt/observability/sample-app
  register: sample_app_compose
  changed_when: true