---
- name: K8S Lab - Limpar resíduos de downloads anteriores
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/helm.tar.gz
    - /tmp/linux-amd64

- name: K8S Lab - Baixar binário oficial do Helm
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-v3.18.6-linux-amd64.tar.gz
    dest: /tmp/helm.tar.gz
    mode: '0644'

- name: K8S Lab - Descompactar Helm
  ansible.builtin.unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp
    remote_src: true

- name: K8S Lab - Instalar Helm no PATH do sistema
  ansible.builtin.copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: '0755'
    remote_src: true

- name: K8S Lab - Validar existência do binário
  ansible.builtin.stat:
    path: /usr/local/bin/helm
  register: helm_binary

- name: K8S Lab - Validar instalação do Helm
  ansible.builtin.command:
    cmd: /usr/local/bin/helm version
  register: helm_version
  changed_when: false

- name: K8S Lab - Exibir versão instalada
  ansible.builtin.debug:
    msg: "{{ helm_version.stdout }}"