---
- name: K8S Lab - Limpar resíduos de downloads anteriores
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/helm.tar.gz
    - /tmp/linux-amd64

- name: K8S Lab - Baixar binário oficial do Helm
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-v3.18.6-linux-amd64.tar.gz
    dest: /tmp/helm.tar.gz
    mode: '0644'

- name: K8S Lab - Descompactar Helm
  ansible.builtin.unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp
    remote_src: true

- name: K8S Lab - Instalar Helm no PATH do sistema
  ansible.builtin.copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: '0755'
    remote_src: true

- name: K8S Lab - Validar existência do binário
  ansible.builtin.stat:
    path: /usr/local/bin/helm
  register: helm_binary

- name: K8S Lab - Validar instalação do Helm
  ansible.builtin.command:
    cmd: /usr/local/bin/helm version
  register: helm_version
  changed_when: false

- name: K8S Lab - Exibir versão instalada
  ansible.builtin.debug:
    msg: "{{ helm_version.stdout }}"

- name: K8S Lab - Baixar e instalar o kubectl (CLI do Kubernetes)
  ansible.builtin.get_url:
    url: https://k8s.io
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: K8S Lab - Baixar e instalar o Kind (Kubernetes in Docker)
  ansible.builtin.get_url:
    url: https://k8s.io
    dest: /usr/local/bin/kind
    mode: '0755'

- name: K8S Lab - Criar o cluster Kubernetes via Kind (Usando caminho absoluto)
  ansible.builtin.command:
    cmd: /usr/local/bin/kind create cluster --name k8s-sre --image kindest/node:v1.30.0
  register: kind_out
  failed_when: kind_out.rc != 0 and "already exists" not in kind_out.stderr
  changed_when: "'creating node' in kind_out.stdout"

- name: K8S Lab - Conectar o cluster Kind na rede do Docker Compose do Zabbix
  ansible.builtin.command:
    cmd: docker network connect observability_obs-net k8s-sre-control-plane
  register: net_out
  failed_when: net_out.rc != 0 and "already exists" not in net_out.stderr
  changed_when: net_out.rc == 0