---
- name: Master Playbook - SRE Lab Bootstrap
  hosts: lab
  become: true
  gather_facts: true

  roles:
    - common
    - docker
    - zabbix_docker
    - k3s
    - sample_app_docker
    - sample_app_k8s
