---
- name: Criar pasta da stack do Zabbix
  file:
    path:  /opt/observability/zabbix
    state: directory
    mode: '0755'

- name: Copiar arquivo do docker-compose estático para o lab
  copy:
    src: docker-compose.yml
    dest: /opt/observability/zabbix/docker-compose.yml
    mode: '0644'

- name: Subir os containers do Zabbix Server e Web Frontend
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /opt/observability/zabbix
  register: compose_out
  changed_when: "'Creating' in compose_out.stdout or 'Starting' in compose_out.stdout or 'Building' in compose_out.stdout"
